name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.39.0'
      
      - name: Build WASM
        run: |
          cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js .
          tinygo build -o main.wasm -target wasm main_wasm.go
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
